### ISSUE TITLE
Create GitHub Page pointing to /LocalStore/index.html

### ISSUE THREAD

**Issue by grutt** [udacity/FSND#1]
Please create a github page pointing to: https://github.com/udacity/FSND/blob/master/LocalStore/index.html

then update coco link to reflect the public URL:
https://coco.udacity.com/nanodegrees/nd004-beta/locale/en-us/versions/2.0.0/parts/858461/modules/850001/lessons/850004/concepts/857086#

**Comment by AbeFeinberg** [comment]
Done! Have a look at the page in CoCo and make sure it's working the way you want.
