### ISSUE TITLE
SVG are not displayed

### ISSUE THREAD

**Issue by rubendata** [udacity/FSND#109]
Hi team,
in your Question.js and QuestionView.js there is wrong code that leads to svg are not displayed in your starter code. Please change to:
Question.js line 23: only if category is not undefined (=true) do something. and the category type is needed and in lowercase
{category && <img className="category" src={`${category.type.toLowerCase()}.svg`}/>} 

QuestionView.js lin 132: again also the type is needed in lowercase
<img className="category" src={`${this.state.categories[id]['type'].toLowerCase()}.svg`}/>

**Comment by SudKul** [comment]
Thanks, @rubendata 
Accepted your suggestion. See [Question.js](https://github.com/udacity/FSND/blob/e024c1150e66d68f0197599290085b0dd7f42413/projects/02_trivia_api/starter/frontend/src/components/Question.js#L22) and [QuestionView.js](https://github.com/udacity/FSND/blob/fbd33fe6600b5567dc22de2c8fefa1571e86d839/projects/02_trivia_api/starter/frontend/src/components/QuestionView.js#L131)
Thank you!
