### ISSUE TITLE
Changes to the Auth0 Audiance Name

### ISSUE THREAD

**Issue by nchathu2014** [udacity/FSND#113]
https://github.com/udacity/FSND/blob/e9c096dd10db256a510513b939c86fe648aeab86/BasicFlaskAuth/app.py#L120

`@app.route('/headers')
@requires_auth
def headers(payload):
    print(payload)
    return 'Access Granted'`

route to '/headers' will not work (will give 404), in Auth0 account creation, gave the audiance name as 'images', we have to change the name in Auth0 side

Thank you!
Cheers!!!

**Comment by SudKul** [comment]
Hi @nchathu2014 
Please raise a PR along with a detailed description of the error and resolution. 
Thank you.
