### ISSUE TITLE
typed-ast 1.3.5 is not supported in Python3.9

### ISSUE THREAD

**Issue by mukuns** [udacity/FSND#120]
Please update the version of typed-ast in requirement.txt, as 1.3.5 is currently not supported in python 3.9
`Running setup.py install for typed-ast ... error
    ERROR: Command errored out with exit status 1:`

**Comment by SudKul** [comment]
Hi @mukuns 
Currently, all our code has been tested on Python 3.6
Please have the same virtual environment for a seamless experience. 
Thanks
