### ISSUE TITLE
There is no "num_shows" in the example static data

### ISSUE THREAD

**Issue by julianovmartins** [udacity/FSND#135]
https://github.com/udacity/FSND/blob/2d1197d98d4ef65520b842c6345d8bac1688ed48/projects/01_fyyur/starter_code/app.py#L433

Suggestion:
Remove that TODO comment line or add the "num_shows" key to static data and the "templates/pages/shows.html".

**Comment by ronny-udacity** [comment]
Thank you for raising the issue. The line has been removed.
