### ISSUE TITLE
Correction in the text of the Instructions section

### ISSUE THREAD

**Issue by julianovmartins** [udacity/FSND#141]
## README.md file: 

 In Instructions section:

> Using SQLAlchemy, set up normalized models for the objects we support in our web app in the Models section of app.py. Check out the sample pages provided at /artists/1, /venues/1, and /shows/1 for examples of the data we want to model, using all of the learned best practices in database schema design. Implement missing model properties and relationships using database migrations via Flask-Migrate.

Udacity does not provide the `/shows/<int:show_id>` endpoint for a `/shows/1` URL.

This should be updated to:

> Using SQLAlchemy, set up normalized models for the objects we support in our web app in the Models section of app.py. Check out the sample pages provided at /artists/1, /venues/1, and /shows for examples of the data we want to model, using all of the learned best practices in database schema design. Implement missing model properties and relationships using database migrations via Flask-Migrate.

**Comment by ronny-udacity** [comment]
Thank you. It's been updated.
