### ISSUE TITLE
'BasicFlaskAuth' exercise requires package updates due to a bug.

### ISSUE THREAD

**Issue by nooreldeensalah** [udacity/FSND#142]
https://github.com/udacity/FSND/blob/2d1197d98d4ef65520b842c6345d8bac1688ed48/BasicFlaskAuth/requirements.txt#L17

Hi,

I tried following along with the [`BasicFlaskAuth`](https://github.com/udacity/FSND/tree/master/BasicFlaskAuth) exercise, but I would keep getting this error when I try doing a GET request.
`TypeError: required field "type_ignores" missing from Module`

After some searching, it turned out to be a bug that existed in version `0.15.4` of `Werkzeug` requirement, according to this [changelog ](https://werkzeug.palletsprojects.com/en/1.0.x/changes/#version-0-15-5) on their documentation website.

Thus, a possible fix would be to change the referenced line to `Werkzeug==0.15.5` or to a later version.

After updating that line, and trying to do the GET request again, it worked with no errors.

Hopefully this issue is fixed such that it doesn't cause frustration to future learners.

Regards,

**Comment by ronny-udacity** [comment]
Thank you for raising the issue. The requirement.txt has been updated.
