### ISSUE TITLE
forms.py phone field TODO

### ISSUE THREAD

**Issue by ant1fact** [udacity/FSND#151]
https://github.com/udacity/FSND/blob/db539dda0fc7950f7572f6ecced943e2534c008c/projects/01_fyyur/starter_code/forms.py#L195

Hello, is the above comment meant to appear for the phone field or is it by mistake?
For now I added validation logic in my submission for the state selector but not the phone field.

Thanks.

**Comment by SudKul** [comment]
Hi @ant1fact 
Have you raised the concern above with Mentors on the https://knowledge.udacity.com/ platform? We encourage discussing individual issues on knowledge hub to have other learners visibility as well. 

If you got the answer, please share your findings with us here.
