### ISSUE TITLE
Jinja2 and Python 3.10

### ISSUE THREAD

**Issue by julianovmartins** [udacity/FSND#166]
To work with Python 3.10, the `Jinja2` version must be:

```
Jinja2==3.0
```

https://github.com/udacity/FSND/blob/3da13c05c0f2fec6f4880a3e1ddf6b1703035b0d/projects/01_fyyur/starter_code/requirements.txt

**Comment by SudKul** [comment]
Thanks, @julianovmartins 
Currently, the Udacity classroom workspace is not supporting the Python 3.10.
