### ISSUE TITLE
Collections.Callable and Python 3.10

### ISSUE THREAD

**Issue by julianovmartins** [udacity/FSND#167]
To work with Python 3.10, the `collections.Callable` must be set to:

```
import collections
import collections.abc
collections.Callable = collections.abc.Callable
```

https://github.com/udacity/FSND/blob/3da13c05c0f2fec6f4880a3e1ddf6b1703035b0d/projects/01_fyyur/starter_code/app.py#L4

**Comment by SudKul** [comment]
Thanks, @julianovmartins

**Comment by Fast-Brain** [comment]
This is very helpful.
  
Thank you, @julianovmartins
