### ISSUE TITLE
 Incorrect or unclear todo

### ISSUE THREAD

**Issue by InfinityByTen** [udacity/FSND#23]
In the following piece of code, a task is given to implement "enum restrictions"
https://github.com/udacity/FSND/blob/ee22b4ee899dd9a4df34a6551ae96a0b0bd020ae/projects/01_fyyur/starter_code/forms.py#L191
However in the code below, the enum is constrained by a choices menu and has a validator as:

`genres = SelectMultipleField(
        # TODO implement enum restriction
        'genres', validators=[DataRequired()],
        choices=[
            ('Alternative', 'Alternative'),
            ('Blues', 'Blues'),
            ...
            ...
`
It's not clear what restrictions are needed to be implemented. Choices and the validator seem to ensuring that the correct enum is sent and at least one is chosen.

A similar todo is found here:
https://github.com/udacity/FSND/blob/ee22b4ee899dd9a4df34a6551ae96a0b0bd020ae/projects/01_fyyur/starter_code/forms.py#L92

And also here, which seems to have no need for any enums altogether.
https://github.com/udacity/FSND/blob/ee22b4ee899dd9a4df34a6551ae96a0b0bd020ae/projects/01_fyyur/starter_code/forms.py#L216

I would ideally open a PR for this, but since I haven't submitted it yet, I would ask the creators of the task to review this and fix these todos. Or alternatively clarify what kind of restrictions are expected.

**Comment by MattiooFR** [comment]
Hello @InfinityByTen, did you submit your project ? Was there any error as you say ?

**Comment by InfinityByTen** [comment]
I did and I didn't add any enum restriction. The one in line # `216` is absolutely useless. That should definitely go away. 

For the other two, however, there is a bit of a reasoning why would you put an extra check, despite the form allowing only a limited number of choices. Since the form is only a template and visible to the end user via the browser and doesn't particularly **enforce** the request being limited to just the stated options, the app is technically unsafe. 

So this might be just reviewer dependent, but in the real world, one must ensure that the app controls the enforcement of good  behaviour of the request and doesn't rely on just the frontend for that. You want to check that the body you receive is therefore consistent with what you expect and allow. Otherwise you might be risking a crashing of your service.

**Comment by SudKul** [comment]
Hey @InfinityByTen 
Your observation points related to safety are pretty much valid. However, these concerns were not among the project 1 objectives. 
Thank you.
