### ISSUE TITLE
Starter code has error in fortmat_datetime function

### ISSUE THREAD

**Issue by ProcureEminenceMB** [udacity/FSND#39]
If the locale is not specified when calling babel.dates.format_datetime(), it throws the following error:
AttributeError: 'NoneType' object has no attribute 'days'

The fix on my Windows 10 machine is the following:
return babel.dates.format_datetime(date, format, locale='en')

**Comment by eli-halych** [comment]
That fixed it on my Windows 10 machine!

**Comment by robinlamb** [comment]
I created a pull request that contains this fix, along with some other problems.  [https://github.com/udacity/FSND/pull/117](url)
