### ISSUE TITLE
FlaskWTF Deprecation Warning: "flask_wtf.Form" has been renamed to "FlaskForm"

### ISSUE THREAD

**Issue by p6l-richard** [udacity/FSND#41]
According to flask-wtf the Class named `Form` will be removed.

**Comment by SudKul** [comment]
Thanks, @p6l-richard for the update. 
We will take this up during the overall course maintenance. Meanwhile, refer to this [discussion](https://github.com/pallets/flask/issues/2488) for an interim resolution.
