### ISSUE TITLE
../frontend/public/*.svg files not displaying. 

### ISSUE THREAD

**Issue by irzelindo** [udacity/FSND#5]
*.svg icons are not displaying on the app page.
file names must be capitalized.

**Comment by SudKul** [comment]
Hi @irzelindo 
Though we are a little late in responding, we cannot replicate the issue you are facing. 
Can you provide us specific error details or submit a PR with your proposed changes?
Thank you. 
 - 
 -

**Comment by SudKul** [comment]
To mitigate the risk of letter-case (lower/upper), we have converted the file name to lower case. For example, see this [commit](https://github.com/udacity/FSND/commit/fbd33fe6600b5567dc22de2c8fefa1571e86d839). 

Now a user can change the SVG files, with a different name.
