### ISSUE TITLE
requirement.txt - Werkzeug version

### ISSUE THREAD

**Issue by yaraxxx** [udacity/FSND#84]
Hey, 
I noticed that Werkzeug version in requirement.txt is 0.15.4 . Which apparently has some issue showing an error when running ` falsk run` 
The error message was ` TypeError: required field "type_ignores" missing from Module` and the solution to this error was upgrading Werkzeug to Werkzeug-1.0.1.
**Maybe you should change the version in requirement.txt**

**Comment by edwinaquino** [comment]
Same here. I kept getting 500 errors. Found solution here:
https://stackoverflow.com/questions/60140174/basic-flask-app-not-running-typeerror-required-field-type-ignores-missing-fr

After I changed from Werkzeug==0.15.4 to Werkzeug==0.15.5 in requirements.txt - it worked

**Comment by SudKul** [comment]
Thanks, @edwinaquino and @yaraxxx for reporting this issue. 
We have updated the Werkzeug package to 0.15.4
