### ISSUE TITLE
Wrong instructions

### ISSUE THREAD

**Issue by MarcoRezkallah** [udacity/FSND#98]
/projects/01_fyyur/starter_code/README.md > Instructions (number 6)
[https://github.com/udacity/FSND/blob/master/projects/01_fyyur/starter_code/README.md](url)

written:
 
Using SQLAlchemy, set up normalized models for the objects we support in our web app in the Models section of app.py. Check out the sample pages provided at **/artists/1**, /venues/1, and **/shows/1** for examples of the data we want to model, using all of the learned best practices in database schema design. Implement missing model properties and relationships using database migrations via Flask-Migrate.

but it should be:

Using SQLAlchemy, set up normalized models for the objects we support in our web app in the Models section of app.py. Check out the sample pages provided at **/artists/4**, /venues/1, and **/shows** for examples of the data we want to model, using all of the learned best practices in database schema design. Implement missing model properties and relationships using database migrations via Flask-Migrate.

or else it'll throw exception

**Comment by SudKul** [comment]
It has been fixed now. 
Thank you for your inputs. 👍
